### ISSUE TITLE
unconnected tag 

### ISSUE THREAD

**Issue by mrobl320** [anjennings/Tom80#1]
On the schematic for the eeprom programmer there is a VUSB tag that is not connected to anything so does it go to some pin of something or not?

**Comment by anjennings** [comment]
VUSB should be connected to a capacitor if operating at 5V, per the datasheet, good catch.
This was added in a later version of the schematic that I have apparently failed to upload.
Sorry about any confusion this may have caused.

![image](https://user-images.githubusercontent.com/16313288/111790597-5ce34b00-8890-11eb-81e6-bec997e6f290.png)

**Comment by anjennings** [comment]
New version of schematic is now in master

![image](https://user-images.githubusercontent.com/16313288/111792248-1131a100-8892-11eb-8d72-b50c64556ce7.png)
